on:
  push:
    branches:
    - feature

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: pull-request
      uses: repo-sync/pull-request@v2
      with:
        destination_branch: "main"
        github_token: ${{ secrets.GITHUB_TOKEN }}
        pr_title: "Pull Request 12" # Title of pull request
        pr_body: "I want to merge from feature branch to main"
        pr_reviewer: "YAbdul" 